name: Generate Snake Game

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC
  workflow_dispatch: # Allows manual trigger

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Platane/snk@v3
        with:
          github_user_name: Bammcool2011
          outputs: |
            dist/github-contribution-grid-snake.svg
      - uses: actions/upload-artifact@v4
        with:
          name: snake-svg
          path: dist/github-contribution-grid-snake.svg
      - name: Push to output branch
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git checkout -b output || git checkout output
          cp dist/github-contribution-grid-snake.svg .
          git add github-contribution-grid-snake.svg
          git commit -m "Update snake animation" || echo "No changes to commit"
          git push origin output --force
